// src/utils/categories.js

export const categories = [
  "Men's Fashion",
  "Women's Fashion",
  "Shoes & Footwear",
  "Bags & Luggage",
  "Jewelry & Watches",
  "Accessories",
  "Phones & Tablets",
  "Laptops & Computers",
  "TVs & Audio",
  "Cameras & Drones",
  "Gaming & Consoles",
  "Computer Accessories",
  "Home & Kitchen",
  "Furniture",
  "Bedding & Bath",
  "Home Appliances",
  "Tools & DIY",
  "Garden & Outdoor",
  "Health & Beauty",
  "Sports & Fitness",
  "Books & Media",
  "Toys & Games",
  "Baby & Kids",
  "Automotive",
  "Groceries & Pets",
  "Other",
];